// Comprehensive list of valid 5-letter English words for guess validation
// Includes all answer words plus common 5-letter words

const VALID_WORDS: string[] = [
  'aback', 'abide', 'abler', 'abode', 'abort', 'about', 'above', 'abuse', 'acorn', 'acrid',
  'acted', 'actor', 'acute', 'adage', 'adapt', 'added', 'adept', 'adieu', 'admit', 'adopt',
  'adore', 'adorn', 'adult', 'affix', 'afire', 'afoot', 'afore', 'after', 'again', 'agape',
  'agent', 'agile', 'aging', 'aglow', 'agony', 'agora', 'agree', 'ahead', 'aided', 'aimed',
  'aisle', 'alarm', 'album', 'alert', 'algae', 'alien', 'align', 'alike', 'alive', 'alley',
  'allow', 'alloy', 'aloft', 'alone', 'along', 'aloof', 'aloud', 'alpha', 'altar', 'alter',
  'amaze', 'amber', 'amend', 'amids', 'ample', 'amply', 'amuse', 'angel', 'anger', 'angle',
  'angry', 'anime', 'ankle', 'annul', 'anvil', 'aorta', 'apart', 'aphid', 'apnea', 'apple',
  'apply', 'apron', 'aptly', 'arbor', 'arena', 'argue', 'arise', 'armor', 'aroma', 'array',
  'arrow', 'arson', 'ascot', 'aside', 'asked', 'askew', 'aspen', 'assay', 'asset', 'atlas',
  'attic', 'audio', 'audit', 'aunty', 'avert', 'avian', 'avoid', 'await', 'awake', 'award',
  'aware', 'awash', 'awful', 'awoke', 'axial', 'axiom', 'azure',

  'bacon', 'badge', 'badly', 'bagel', 'baggy', 'baker', 'baler', 'balmy', 'banal', 'banjo',
  'barge', 'baron', 'basal', 'basic', 'basil', 'basin', 'basis', 'basso', 'batch', 'bater',
  'bathe', 'baton', 'beach', 'beady', 'beaky', 'beast', 'being', 'belch', 'below', 'bench',
  'berry', 'berth', 'bible', 'bicep', 'bigot', 'bilge', 'binge', 'biome', 'biped', 'birch',
  'birth', 'bison', 'biter', 'black', 'blade', 'blame', 'bland', 'blank', 'blare', 'blast',
  'blaze', 'bleak', 'bleat', 'bleed', 'blend', 'bless', 'blimp', 'blind', 'blink', 'bliss',
  'blitz', 'bloat', 'block', 'blond', 'blood', 'bloom', 'blown', 'blues', 'bluff', 'blunt',
  'blurt', 'blush', 'board', 'boast', 'bonus', 'bony', 'booth', 'booty', 'bound', 'bower',
  'boxer', 'brace', 'braid', 'brail', 'brain', 'brake', 'brand', 'brash', 'brass', 'brave',
  'bravo', 'brawl', 'bread', 'break', 'breed', 'briar', 'bribe', 'brick', 'bride', 'brief',
  'brine', 'bring', 'brink', 'brisk', 'broad', 'broil', 'broke', 'brood', 'brook', 'brown',
  'bruit', 'brush', 'brute', 'buddy', 'budge', 'bugle', 'build', 'built', 'bulge', 'bulky',
  'bunch', 'bunny', 'burly', 'burnt', 'burst', 'bused', 'bushy', 'butte', 'butyl', 'buxom',
  'buyer',

  'cabin', 'cable', 'cacao', 'caddy', 'cadet', 'caged', 'cagey', 'cairn', 'camel', 'cameo',
  'campy', 'canal', 'candy', 'canny', 'canon', 'caped', 'caper', 'caput', 'carat', 'cargo',
  'carol', 'carry', 'carte', 'carve', 'caste', 'catch', 'cater', 'cause', 'cease', 'cedar',
  'celli', 'cello', 'chain', 'chair', 'chalk', 'champ', 'chant', 'chaos', 'charm', 'chart',
  'chase', 'chasm', 'cheap', 'cheat', 'check', 'cheek', 'cheer', 'chess', 'chest', 'chewy',
  'chick', 'chief', 'child', 'chill', 'chime', 'choir', 'choke', 'chord', 'chore', 'chunk',
  'churn', 'chute', 'cider', 'cigar', 'cinch', 'circa', 'cited', 'civet', 'civic', 'civil',
  'clack', 'claim', 'clamp', 'clang', 'clank', 'clash', 'clasp', 'class', 'clave', 'clean',
  'clear', 'cleat', 'cleft', 'clerk', 'click', 'cliff', 'climb', 'cling', 'clink', 'cloak',
  'clock', 'clone', 'close', 'cloth', 'cloud', 'clout', 'clown', 'clued', 'clump', 'clums',
  'coach', 'coast', 'cocoa', 'colic', 'colon', 'color', 'comet', 'comic', 'conga', 'congo',
  'conic', 'coral', 'corer', 'corky', 'corps', 'couch', 'cough', 'could', 'count', 'courn',
  'court', 'coven', 'cover', 'covey', 'cower', 'coyly', 'crack', 'craft', 'cramp', 'crane',
  'crank', 'crash', 'crate', 'crave', 'crawl', 'craze', 'crazy', 'cream', 'credo', 'creed',
  'creek', 'creep', 'crepe', 'crept', 'cress', 'crest', 'crick', 'crime', 'crimp', 'crisp',
  'croak', 'crony', 'crook', 'cross', 'croup', 'crowd', 'crown', 'crude', 'cruel', 'crumb',
  'crush', 'crust', 'crypt', 'cubed', 'cubic', 'cuddy', 'cuff', 'culls', 'culpa', 'cults',
  'cumin', 'cupid', 'curbs', 'curds', 'cured', 'cures', 'curia', 'curio', 'curly', 'curry',
  'curse', 'curve', 'curvy', 'cushy', 'cutie', 'cyber', 'cycle', 'cynic',

  'daddy', 'daily', 'dairy', 'daisy', 'dance', 'dandy', 'dared', 'darky', 'darned', 'darts',
  'dated', 'datum', 'daunt', 'dealt', 'death', 'debar', 'debit', 'debut', 'decaf', 'decal',
  'decay', 'decor', 'decoy', 'decry', 'defer', 'deify', 'deign', 'deist', 'deity', 'delay',
  'delta', 'delve', 'demon', 'demur', 'dense', 'depot', 'depth', 'derby', 'deter', 'deuce',
  'devil', 'diary', 'dicey', 'diddy', 'digit', 'dilly', 'dimer', 'dimly', 'dinar', 'dined',
  'dingy', 'dinky', 'diode', 'dirge', 'dirty', 'disco', 'ditch', 'ditto', 'ditty', 'divan',
  'dived', 'divot', 'dizzy', 'dodge', 'dodgy', 'dogma', 'dolly', 'donor', 'dopey', 'dorky',
  'dose', 'doted', 'doubt', 'dough', 'dovey', 'dowdy', 'dowel', 'downy', 'dowry', 'dozen',
  'draft', 'drain', 'drake', 'drama', 'drank', 'drape', 'drawl', 'drawn', 'dread', 'dream',
  'dress', 'dried', 'drier', 'drift', 'drill', 'drink', 'drive', 'droid', 'droll', 'drone',
  'drool', 'droop', 'dross', 'drove', 'drown', 'drums', 'drunk', 'dryer', 'dryly', 'duchy',
  'dully', 'dummy', 'dumpy', 'dunce', 'dune', 'dungy', 'dunno', 'duomo', 'duped', 'dural',
  'dusty', 'dutch', 'duvet', 'dwarf', 'dwell', 'dwelt', 'dying',

  'eager', 'eagle', 'eared', 'early', 'earth', 'eaten', 'ebony', 'eclat', 'edema', 'edged',
  'edict', 'edify', 'educe', 'eerie', 'egads', 'egged', 'egret', 'eight', 'eject', 'elate',
  'elbow', 'elder', 'elect', 'elegy', 'elfin', 'elide', 'elite', 'elope', 'elude', 'elves',
  'email', 'embed', 'ember', 'emcee', 'emery', 'emote', 'empty', 'enact', 'ended', 'endow',
  'enemy', 'enjoy', 'ennui', 'enrol', 'ensue', 'enter', 'entry', 'envoy', 'epoch', 'epoxy',
  'equal', 'equip', 'erase', 'erect', 'error', 'erupt', 'essay', 'ester', 'ether', 'ethic',
  'ethos', 'evade', 'event', 'every', 'evict', 'evoke', 'exact', 'exalt', 'excel', 'exert',
  'exile', 'exist', 'expel', 'extol', 'extra', 'exult', 'eying',

  'fable', 'facet', 'faint', 'fairy', 'faith', 'false', 'fancy', 'fanny', 'farce', 'fatal',
  'fated', 'fatty', 'fault', 'feast', 'fecal', 'feign', 'feint', 'fella', 'felon', 'femur',
  'fence', 'feral', 'ferry', 'fetch', 'fetid', 'fetus', 'feud', 'fever', 'fiery', 'fifth',
  'fifty', 'fight', 'filch', 'filed', 'filet', 'filmy', 'filth', 'final', 'finch', 'finer',
  'finis', 'fired', 'firms', 'first', 'firth', 'fishy', 'fiver', 'fixed', 'fixer', 'fizzy',
  'fjord', 'flack', 'flags', 'flail', 'flair', 'flake', 'flaky', 'flame', 'flank', 'flare',
  'flash', 'flask', 'fleck', 'fleet', 'flesh', 'flick', 'fling', 'flint', 'flirt', 'float',
  'flock', 'flood', 'floor', 'flora', 'floss', 'flour', 'floyd', 'fluff', 'fluid', 'fluke',
  'flume', 'flush', 'flute', 'flyer', 'foamy', 'focal', 'focus', 'fogey', 'foist', 'folks',
  'folly', 'foray', 'force', 'forge', 'forgo', 'forte', 'forth', 'forty', 'forum', 'fossa',
  'fouls', 'found', 'fount', 'foyer', 'frail', 'frame', 'frank', 'fraud', 'freak', 'freed',
  'fresh', 'friar', 'fried', 'frill', 'frisk', 'frock', 'frond', 'front', 'frost', 'froth',
  'frown', 'froze', 'fruit', 'frump', 'fryer', 'fudge', 'fugal', 'fugue', 'fumes', 'fungi',
  'funky', 'funny', 'furor', 'furry', 'fused', 'fussy', 'fuzzy',

  'gaily', 'gator', 'gauze', 'gauzy', 'gavel', 'gawky', 'gayer', 'gayly', 'gazed', 'gazer',
  'gecko', 'geeky', 'gelds', 'genet', 'genre', 'gents', 'genus', 'geode', 'germy', 'ghost',
  'ghoul', 'giant', 'giddy', 'gifts', 'gilds', 'gimpy', 'gipsy', 'giver', 'given', 'glade',
  'gland', 'glare', 'glass', 'glaze', 'gleam', 'glean', 'glide', 'glint', 'glitz', 'gloat',
  'globe', 'gloom', 'glory', 'gloss', 'glove', 'glows', 'glued', 'gluey', 'gluon', 'glyph',
  'gnarl', 'gnash', 'gnome', 'godly', 'going', 'golem', 'golly', 'goner', 'goofy', 'goose',
  'gored', 'gorge', 'gorse', 'gotta', 'gouge', 'gourd', 'gouty', 'gowns', 'grace', 'grade',
  'graft', 'grail', 'grain', 'grand', 'grant', 'grape', 'graph', 'grasp', 'grass', 'grate',
  'grave', 'gravy', 'graze', 'great', 'greed', 'green', 'greet', 'greys', 'grief', 'grill',
  'grime', 'grind', 'grins', 'gripe', 'grist', 'grits', 'groan', 'groin', 'groom', 'grope',
  'gross', 'group', 'grout', 'grove', 'growl', 'grown', 'gruel', 'gruff', 'grunt', 'guard',
  'guava', 'guess', 'guest', 'guide', 'guild', 'guile', 'guilt', 'guise', 'gulch', 'gulfs',
  'gumbo', 'gunky', 'gunny', 'gurdy', 'gurly', 'gurus', 'gushy', 'gusto', 'gusty', 'gutsy',
  'guyed',

  'habit', 'hacky', 'haiku', 'hairy', 'halls', 'halve', 'hammy', 'handy', 'happy', 'hards',
  'hardy', 'harem', 'harpy', 'harsh', 'haste', 'hasty', 'hatch', 'hated', 'hauls', 'haunt',
  'haven', 'havoc', 'hazel', 'hazy', 'heady', 'heals', 'heapy', 'heart', 'heath', 'heave',
  'heavy', 'hedge', 'heels', 'hefty', 'heist', 'helix', 'hello', 'hence', 'herbs', 'heron',
  'heros', 'hider', 'highs', 'hiker', 'hilly', 'hinge', 'hippo', 'hippy', 'hired', 'hitch',
  'hobby', 'hoist', 'hokey', 'hokum', 'holds', 'holly', 'homes', 'honey', 'honks', 'honor',
  'hooch', 'hoods', 'hoofs', 'hooks', 'hooky', 'hoped', 'horde', 'horns', 'horny', 'horse',
  'hotel', 'hotly', 'hound', 'house', 'hovel', 'hover', 'howdy', 'hubby', 'huffy', 'human',
  'humid', 'humer', 'humor', 'hunch', 'hunks', 'hunky', 'hurry', 'hurst', 'hushy', 'husky',
  'hutch', 'hydra', 'hyena', 'hymen', 'hyped', 'hyper', 'hyphe',

  'iatro', 'icily', 'icing', 'ideal', 'idiom', 'idiot', 'idled', 'idler', 'idyll', 'igloo',
  'ihram', 'ikats', 'ileac', 'ileum', 'ileus', 'iliac', 'ilium', 'ilks', 'image', 'imago',
  'imbed', 'imbue', 'imide', 'imine', 'imino', 'immix', 'imped', 'impel', 'imply', 'inane',
  'inapt', 'inbox', 'incur', 'index', 'indie', 'inept', 'inert', 'infer', 'infix', 'ingot',
  'inked', 'inlay', 'inlet', 'inner', 'input', 'inset', 'inter', 'intra', 'inure', 'ionia',
  'ionic', 'iotas', 'irate', 'irids', 'irish', 'irks', 'irony', 'isles', 'islet', 'issue',
  'items', 'ither', 'ivied', 'ivory',

  'jabot', 'jacks', 'jaded', 'jager', 'jaguar', 'jails', 'jaker', 'jalap', 'jambs', 'jambu',
  'james', 'jammy', 'janes', 'janky', 'japes', 'jarls', 'jasps', 'jaunt', 'javel', 'jawed',
  'jawan', 'jawed', 'jazzy', 'jeans', 'jebel', 'jelly', 'jenny', 'jerks', 'jerky', 'jests',
  'jets', 'jewel', 'jibed', 'jiffy', 'jilts', 'jimmy', 'jingo', 'jinks', 'jinni', 'jinns',
  'jived', 'jivy', 'jocks', 'joeys', 'johns', 'joins', 'joint', 'joist', 'joked', 'joker',
  'jolly', 'jolts', 'joule', 'joust', 'jowls', 'jowly', 'joyed', 'judge', 'jugal', 'juice',
  'juicy', 'julep', 'jumbo', 'jumps', 'jumpy', 'junco', 'junks', 'junky', 'junta', 'jural',
  'jurat', 'jurel', 'juror', 'justs', 'jutes', 'jutty',

  'kabab', 'kabar', 'kabob', 'kadis', 'kafir', 'kagus', 'kaifs', 'kails', 'kains', 'kakas',
  'kakis', 'kalam', 'kales', 'kalif', 'kalis', 'kalki', 'kanae', 'kanas', 'kanji', 'kants',
  'kaons', 'kapok', 'kappa', 'kaput', 'karat', 'karma', 'karns', 'karoo', 'karst', 'karts',
  'kasha', 'katas', 'kauri', 'kaury', 'kavas', 'kayak', 'kayos', 'kazoo', 'kebab', 'kebob',
  'keels', 'keens', 'keeps', 'keets', 'keeve', 'kefir', 'keirs', 'kelep', 'kelps', 'kelpy',
  'kelts', 'kemps', 'kempt', 'kenaf', 'kendo', 'kenos', 'kente', 'keppi', 'kepis', 'kerbs',
  'kerfs', 'kerma', 'kernel', 'kerns', 'keros', 'kests', 'ketas', 'ketch', 'ketol', 'kette',
  'kexes', 'keyed', 'khadi', 'khafs', 'khaki', 'khans', 'khaph', 'khats', 'kheda', 'kheer',
  'kibei', 'kibes', 'kibla', 'kicks', 'kicky', 'kiddo', 'kiddy', 'kiefs', 'kiers', 'kikoi',
  'kills', 'kilns', 'kilos', 'kilts', 'kilty', 'kinda', 'kinds', 'kines', 'kings', 'kinin',
  'kinks', 'kinky', 'kinos', 'kiosk', 'kippa', 'kirks', 'kirns', 'kissy', 'kists', 'kited',
  'kiter', 'kites', 'kithe', 'kiths', 'kitty', 'kivas', 'kiwis', 'kluge', 'klutz', 'knack',
  'knaps', 'knawe', 'knead', 'kneed', 'kneel', 'knees', 'knell', 'knelt', 'knife', 'knish',
  'knits', 'knobs', 'knock', 'knoll', 'knops', 'knosp', 'knots', 'knout', 'known', 'knows',
  'knurl', 'koala', 'koans', 'kodak', 'koffs', 'kohen', 'kohls', 'koine', 'kojis', 'kooks',
  'kooky', 'kopek', 'kophs', 'kopje', 'koppa', 'korai', 'koras', 'korat', 'korma', 'koros',
  'korun', 'kotos', 'kraal', 'kraft', 'krait', 'kraut', 'kreep', 'krewe', 'krill', 'krona',
  'krone', 'kroon', 'krubi', 'kudos', 'kudzu', 'kugel', 'kukri', 'kulas', 'kulfi', 'kumys',
  'kurta', 'kurus', 'kusso', 'kutch', 'kvell', 'kvetch',

  'label', 'labor', 'laced', 'lacer', 'laces', 'lacey', 'lacks', 'laden', 'ladle', 'lager',
  'laity', 'lance', 'lanky', 'lapel', 'lapse', 'larch', 'lardy', 'large', 'larky', 'larva',
  'lased', 'laser', 'lasso', 'lasts', 'latch', 'later', 'latex', 'lathe', 'laths', 'latin',
  'latke', 'laude', 'lauds', 'laugh', 'laura', 'lavas', 'laved', 'laver', 'lavis', 'lawed',
  'lawns', 'lawny', 'laws', 'layed', 'layer', 'layin', 'layup', 'lazed', 'lazes', 'leach',
  'leads', 'leady', 'leafs', 'leafy', 'leaks', 'leaky', 'leans', 'leant', 'leaps', 'leapt',
  'learn', 'lease', 'leash', 'least', 'leave', 'ledge', 'leech', 'leeks', 'leers', 'leery',
  'lefts', 'lefty', 'legal', 'leger', 'leggy', 'legit', 'lehrs', 'lehua', 'leman', 'lemma',
  'lemon', 'lemur', 'lends', 'lenos', 'lento', 'leone', 'leper', 'lepta', 'leses', 'lesion',
  'lethal', 'letup', 'leuds', 'levee', 'level', 'lever', 'levin', 'levis', 'lewis', 'lexis',
  'lezza', 'lezzy', 'liana', 'liane', 'liang', 'liany', 'libel', 'liber', 'libra', 'libri',
  'licht', 'licit', 'licks', 'lidar', 'lidos', 'liege', 'liens', 'liers', 'lifer', 'lifts',
  'ligan', 'liger', 'light', 'ligne', 'liked', 'liken', 'liker', 'likes', 'limba', 'limbi',
  'limbo', 'limbs', 'limby', 'limed', 'limen', 'limes', 'limey', 'limit', 'limns', 'limos',
  'limpa', 'limps', 'linac', 'lindy', 'lined', 'linen', 'liner', 'lines', 'liney', 'linga',
  'lings', 'lingy', 'linin', 'links', 'linky', 'linns', 'linos', 'lints', 'linty', 'linum',
  'linux', 'lions', 'lipid', 'lipos', 'lippy', 'liras', 'lirks', 'lirot', 'lisle', 'lisps',
  'lists', 'litai', 'litas', 'liter', 'lithe', 'litho', 'liths', 'litre', 'lived', 'liven',
  'liver', 'lives', 'livid', 'livre', 'llama', 'llano', 'loach', 'loads', 'loafs', 'loams',
  'loamy', 'loans', 'loath', 'lobar', 'lobby', 'lobed', 'lobes', 'local', 'lochs', 'lochs',
  'locks', 'locos', 'locum', 'locus', 'loden', 'lodes', 'lodge', 'loess', 'lofts', 'lofty',
  'logan', 'loges', 'logic', 'logon', 'logos', 'loids', 'loins', 'loire', 'loirs', 'lolls',
  'lolly', 'loner', 'longs', 'loofs', 'looks', 'looms', 'loons', 'loony', 'loops', 'loopy',
  'loose', 'loots', 'loped', 'loper', 'lopes', 'loppy', 'lords', 'lores', 'loris', 'losed',
  'losel', 'loses', 'lossy', 'lotah', 'lotas', 'lotic', 'lotos', 'lotta', 'lotte', 'lotto',
  'lotus', 'louch', 'louis', 'loulu', 'louns', 'louse', 'lousy', 'louts', 'lovat', 'loved',
  'lover', 'lovey', 'lowan', 'lowed', 'lower', 'lowes', 'lowly', 'lowse', 'loxia', 'loxed',
  'loxes', 'loyal', 'luaus', 'lubes', 'lubra', 'lucid', 'lucks', 'lucky', 'lucre', 'luffs',
  'luges', 'lulls', 'lulus', 'lumas', 'lumbar', 'lumen', 'lumer', 'lumps', 'lumpy', 'lunar',
  'lunch', 'lunes', 'lunge', 'lungs', 'lunks', 'lunts', 'lupin', 'lupus', 'lurch', 'lured',
  'lurer', 'lures', 'lurex', 'lurid', 'lurks', 'lusts', 'lusty', 'lutea', 'luted', 'lutes',
  'luxes', 'luxur', 'lyard', 'lyart', 'lycea', 'lycee', 'lycra', 'lymph', 'lynch', 'lyres',
  'lyric', 'lysed', 'lyses', 'lysin', 'lysis', 'lyssa', 'lytic', 'lytta',

  'macaw', 'macho', 'macro', 'madam', 'madly', 'mafia', 'magic', 'magma', 'maize', 'major',
  'maker', 'malad', 'malar', 'malic', 'malty', 'mamma', 'mammy', 'maned', 'mange', 'mango',
  'mangy', 'mania', 'manic', 'manly', 'manna', 'manor', 'manta', 'maple', 'march', 'margo',
  'marin', 'marry', 'marsh', 'mason', 'match', 'mated', 'mater', 'matey', 'maths', 'matin',
  'matte', 'mauls', 'mauve', 'mavin', 'maxed', 'maxim', 'mayer', 'mayor', 'mazed', 'mazel',
  'mazer', 'mazey', 'mealy', 'means', 'meant', 'meaty', 'mecum', 'medal', 'media', 'medic',
  'meets', 'melon', 'melts', 'memos', 'mends', 'mensa', 'mense', 'menta', 'mento', 'meows',
  'merch', 'mercy', 'merer', 'meres', 'merge', 'merit', 'merry', 'mesas', 'meshy', 'mesne',
  'meson', 'messy', 'metal', 'meted', 'meter', 'metes', 'meths', 'metol', 'metre', 'metro',
  'mewed', 'mewls', 'mezes', 'mezzo', 'miaow', 'miasm', 'miaul', 'micas', 'micro', 'midas',
  'midge', 'midis', 'midst', 'miens', 'miffs', 'miffy', 'miggs', 'might', 'miked', 'mikes',
  'mikra', 'milch', 'miler', 'miles', 'milks', 'milky', 'milli', 'mills', 'milos', 'milpa',
  'mimed', 'mimeo', 'mimer', 'mimes', 'mimic', 'mimms', 'minae', 'minas', 'mince', 'mincy',
  'minds', 'mined', 'miner', 'mines', 'mings', 'mingy', 'minim', 'minis', 'minke', 'minks',
  'minor', 'mints', 'minty', 'minus', 'mired', 'mires', 'mirex', 'mirin', 'mirth', 'mirza',
  'misdo', 'miser', 'mises', 'misos', 'missy', 'mists', 'misty', 'miter', 'mites', 'mitis',
  'mitre', 'mitts', 'mixed', 'mixer', 'mixes', 'mixup', 'mizen', 'mobby', 'mobes', 'mobil',
  'moble', 'mocha', 'modal', 'model', 'modem', 'modes', 'modus', 'moggy', 'mogul', 'mohel',
  'mohur', 'molar', 'molas', 'molds', 'moldy', 'moles', 'molls', 'molly', 'molts', 'momes',
  'momma', 'mommy', 'momus', 'monad', 'monal', 'monas', 'monde', 'mondo', 'money', 'monic',
  'monks', 'monte', 'month', 'mooch', 'moods', 'moody', 'mooed', 'mooks', 'moola', 'mools',
  'moons', 'moony', 'moors', 'moory', 'moose', 'moots', 'moped', 'moper', 'mopes', 'mopey',
  'morae', 'moral', 'moran', 'moras', 'morat', 'moray', 'morel', 'mores', 'morns', 'moron',
  'morph', 'morro', 'morse', 'morts', 'mosey', 'mossy', 'mosts', 'motel', 'motes', 'motet',
  'moths', 'mothy', 'motif', 'motor', 'motte', 'motto', 'moues', 'mould', 'moult', 'mound',
  'mount', 'mourn', 'mouse', 'mousy', 'mouth', 'moved', 'mover', 'moves', 'movie', 'mowed',
  'mower', 'moxas', 'moxie', 'mozos', 'mucho', 'mucid', 'mucin', 'mucky', 'mucor', 'mucro',
  'muddy', 'mudra', 'muffs', 'muggy', 'muggs', 'muggy', 'mujik', 'mulch', 'mulct', 'mules',
  'muley', 'mulla', 'mulls', 'mumms', 'mummy', 'mumps', 'munch', 'munge', 'mungo', 'munis',
  'muons', 'mural', 'murky', 'murre', 'murry', 'mused', 'muser', 'muses', 'mushy', 'music',
  'musky', 'mussy', 'musts', 'musty', 'mutch', 'muted', 'muter', 'mutes', 'mutts', 'muzzy',
  'myast', 'myrrh', 'nabob', 'nacho', 'nacre', 'nadir', 'naevi', 'naffs', 'naggy', 'naiad',
  'nails', 'naive', 'naked', 'named', 'namer', 'names', 'nanny', 'narcs', 'nards', 'nares',
  'nasal', 'nasty', 'natal', 'natch', 'nates', 'natty', 'navel', 'naves', 'navvy', 'nears',
  'neats', 'neath', 'necks', 'needs', 'needy', 'negus', 'neigh', 'neons', 'nerds', 'nerdy',
  'nerve', 'nervy', 'nests', 'never', 'neves', 'nevus', 'newel', 'newer', 'newly', 'newsy',
  'nexus', 'nicer', 'niche', 'night', 'nihil', 'nimbi', 'nines', 'ninja', 'ninny', 'ninth',
  'nodal', 'noddy', 'nodes', 'noise', 'noisy', 'nomad', 'nomen', 'nonce', 'nones', 'nooks',
  'nooky', 'noons', 'noose', 'nopal', 'north', 'nosed', 'noses', 'nosey', 'notal', 'notch',
  'noted', 'notes', 'nouns', 'novae', 'novas', 'novel', 'noway', 'nuder', 'nudes', 'nudge',
  'nuked', 'nukes', 'nulls', 'numbs', 'nurse', 'nurtz', 'nutty', 'nyala',

  'oaken', 'oakum', 'oared', 'oases', 'oasis', 'oaten', 'oaths', 'obese', 'obeys', 'objet',
  'oboes', 'occur', 'ocean', 'ocher', 'ochre', 'octad', 'octal', 'octet', 'oddly', 'odium',
  'offal', 'offer', 'often', 'ogled', 'ogler', 'ogres', 'ohias', 'ohmic', 'oiled', 'oiler',
  'oinks', 'okays', 'okras', 'olden', 'older', 'oldie', 'oleic', 'oleum', 'olive', 'ombre',
  'omega', 'onion', 'onset', 'oodles', 'oomph', 'oozed', 'oozes', 'opals', 'opens', 'opera',
  'opine', 'oping', 'opium', 'opted', 'optic', 'orach', 'orals', 'orate', 'orbed', 'orbit',
  'orcas', 'order', 'organ', 'oriel', 'orlop', 'osier', 'other', 'otter', 'ought', 'ounce',
  'ousts', 'outdo', 'outer', 'outgo', 'outre', 'ovals', 'ovary', 'ovate', 'ovens', 'overs',
  'overt', 'ovoid', 'ovule', 'owing', 'owlet', 'owned', 'owner', 'oxbow', 'oxide', 'oxlip',
  'ozone',

  'paced', 'pacer', 'paces', 'pacey', 'pacha', 'pacts', 'paddy', 'padre', 'paean', 'paella',
  'pagan', 'pages', 'paged', 'pager', 'pagod', 'pails', 'pains', 'paint', 'pairs', 'paled',
  'paler', 'pales', 'palms', 'palmy', 'palsy', 'panda', 'panel', 'panes', 'pangs', 'panic',
  'pansy', 'pants', 'panty', 'papal', 'papas', 'papaw', 'paper', 'parch', 'pards', 'pared',
  'parer', 'pares', 'parge', 'paris', 'parka', 'parks', 'parrs', 'parry', 'parse', 'parts',
  'party', 'pasha', 'passe', 'pasta', 'paste', 'pasty', 'patch', 'pated', 'paten', 'patio',
  'patsy', 'patty', 'pause', 'paved', 'paver', 'paves', 'pavid', 'pavin', 'pawed', 'pawer',
  'pawky', 'pawls', 'pawns', 'paxes', 'payed', 'payee', 'payer', 'peace', 'peach', 'peage',
  'peaks', 'peaky', 'peals', 'pearl', 'pears', 'peart', 'pease', 'peaty', 'peavy', 'pecky',
  'pecks', 'pedal', 'pedes', 'pedro', 'peeks', 'peels', 'peens', 'peeps', 'peers', 'peggy',
  'pekoe', 'pelts', 'penal', 'pence', 'pends', 'penes', 'pengo', 'penis', 'penna', 'penne',
  'penni', 'penny', 'peons', 'peony', 'pepla', 'peppy', 'perch', 'percy', 'perdu', 'peril',
  'peris', 'perks', 'perky', 'perms', 'perps', 'perry', 'perse', 'perth', 'perts', 'pesto',
  'pests', 'petal', 'peter', 'petit', 'petre', 'petty', 'pewee', 'pewit', 'pffft', 'phage',
  'phase', 'phial', 'phlox', 'phone', 'phony', 'photo', 'phyla', 'phyle', 'piano', 'picas',
  'picks', 'picky', 'picot', 'piece', 'piers', 'pieta', 'piety', 'piggy', 'piked', 'piker',
  'pikes', 'pilaf', 'piled', 'piles', 'pills', 'pilot', 'pimas', 'pimps', 'pinas', 'pinch',
  'pined', 'pines', 'piney', 'pinko', 'pinks', 'pinky', 'pinon', 'pinto', 'pints', 'pinup',
  'pious', 'piped', 'piper', 'pipes', 'pipet', 'pique', 'pitas', 'pitch', 'pithy', 'piton',
  'pivot', 'pixel', 'pixie', 'pizza', 'place', 'plaid', 'plain', 'plait', 'plane', 'plank',
  'plant', 'plash', 'plate', 'plaza', 'plead', 'pleat', 'plebe', 'plena', 'plied', 'plier',
  'plies', 'plods', 'plops', 'plots', 'plows', 'ploys', 'pluck', 'pluff', 'plugs', 'plumb',
  'plume', 'plump', 'plums', 'plumy', 'plunk', 'plush', 'plyer', 'poach', 'pocks', 'pocky',
  'podgy', 'podia', 'poems', 'poesy', 'poets', 'point', 'poise', 'poked', 'poker', 'pokes',
  'pokey', 'polar', 'poled', 'poler', 'poles', 'polio', 'polis', 'polka', 'polls', 'polyp',
  'poms', 'ponds', 'pones', 'pooch', 'pooey', 'poofs', 'poofy', 'pools', 'poons', 'poops',
  'poori', 'poots', 'popes', 'poppy', 'porch', 'pored', 'pores', 'porgy', 'porks', 'porky',
  'porno', 'ports', 'posed', 'poser', 'poses', 'poset', 'posey', 'posit', 'posse', 'potty',
  'pouch', 'pouff', 'poufs', 'pound', 'pours', 'pouts', 'pouty', 'power', 'poxed', 'poxes',
  'prams', 'prank', 'prate', 'prats', 'prawn', 'prays', 'preen', 'preps', 'press', 'prest',
  'preys', 'price', 'prick', 'pricy', 'pride', 'pried', 'prier', 'pries', 'prigs', 'prime',
  'primo', 'primp', 'prink', 'print', 'prior', 'prise', 'prism', 'privy', 'prize', 'probe',
  'prods', 'proem', 'profs', 'progs', 'prole', 'promo', 'proms', 'prone', 'prong', 'proof',
  'props', 'prose', 'proso', 'prost', 'proxy', 'prude', 'prune', 'pruta', 'pryer', 'psalm',
  'pseud', 'pshaw', 'psoas', 'pucks', 'pudgy', 'puffs', 'puffy', 'puked', 'pukes', 'pukka',
  'pulps', 'pulpy', 'pulse', 'pumas', 'pumps', 'punks', 'punky', 'punto', 'punts', 'punty',
  'pupae', 'pupal', 'pupas', 'pupil', 'puppy', 'puree', 'purer', 'purge', 'purim', 'purls',
  'purrs', 'purse', 'pursy', 'purty', 'puses', 'pushy', 'pussy', 'putts', 'putty', 'pygmy',
  'pylon', 'pyric', 'pyxed', 'pyxes', 'pyxis',

  'quack', 'quads', 'quaff', 'quail', 'quake', 'quaky', 'qualm', 'quant', 'quare', 'quark',
  'quart', 'quash', 'quasi', 'quays', 'queen', 'queer', 'quell', 'query', 'quest', 'queue',
  'quick', 'quiet', 'quiff', 'quill', 'quilt', 'quirk', 'quite', 'quits', 'quoin', 'quoit',
  'quota', 'quote', 'quoth',

  'tabby', 'table', 'taboo', 'tacit', 'tacky', 'taffy', 'taint', 'taken', 'taker', 'tales',
  'talky', 'tally', 'talon', 'tamed', 'tamer', 'tango', 'tangy', 'tanka', 'tapir', 'tardy',
  'tarot', 'taste', 'tasty', 'tatty', 'taunt', 'tawny', 'teach', 'teary', 'tease', 'teddy',
  'teeth', 'tempo', 'tempt', 'tenet', 'tenor', 'tense', 'tenth', 'tepid', 'terms', 'terry',
  'terse', 'tests', 'testy', 'thank', 'theft', 'their', 'theme', 'there', 'these', 'thick',
  'thief', 'thigh', 'thill', 'thing', 'think', 'third', 'thong', 'thorn', 'those', 'three',
  'threw', 'throb', 'throw', 'thrum', 'thumb', 'thump', 'thyme', 'tiara', 'tibia', 'tidal',
  'tiger', 'tight', 'tilde', 'timed', 'timer', 'times', 'timid', 'tinge', 'tinny', 'tipsy',
  'tired', 'titan', 'tithe', 'title', 'toast', 'today', 'toddy', 'token', 'tonal', 'tonga',
  'tonic', 'tooth', 'topaz', 'topic', 'torch', 'torso', 'total', 'touch', 'tough', 'towel',
  'tower', 'toxic', 'trace', 'track', 'trade', 'trail', 'train', 'trait', 'trash', 'trawl',
  'tread', 'treat', 'trend', 'triad', 'trial', 'tribe', 'trick', 'tried', 'tries', 'trill',
  'tripe', 'trite', 'troll', 'troop', 'trope', 'trout', 'truce', 'truck', 'truly', 'trump',
  'trunk', 'truss', 'trust', 'truth', 'tryst', 'tubal', 'tubby', 'tulip', 'tummy', 'tumor',
  'tuned', 'tuner', 'tunes', 'tunic', 'turbo', 'tutor', 'tweet', 'twice', 'twine', 'twirl',
  'twist', 'tying',

  'ultra', 'umbel', 'umber', 'umbra', 'uncle', 'uncut', 'under', 'undid', 'undue', 'unfed',
  'unify', 'union', 'unite', 'unity', 'unlit', 'unset', 'untie', 'until', 'unwed', 'unzip',
  'upper', 'upset', 'urban', 'urged', 'urger', 'urine', 'usage', 'users', 'usher', 'usual',
  'usurp', 'usury', 'utter',

  'vacua', 'vacuo', 'vadge', 'vague', 'vagus', 'vails', 'vairs', 'vakil', 'vales', 'valet',
  'valid', 'valor', 'value', 'valve', 'vamps', 'vampy', 'vance', 'vanda', 'vaned', 'vanes',
  'vangs', 'vapid', 'vapor', 'varas', 'varia', 'vario', 'varix', 'varna', 'varus', 'varve',
  'vasty', 'vates', 'vault', 'vaunt', 'veals', 'vealy', 'veeps', 'veers', 'veery', 'vegan',
  'vegem', 'vegie', 'veils', 'veins', 'veiny', 'velar', 'velds', 'veldt', 'velum', 'venae',
  'venal', 'vends', 'venge', 'venin', 'venom', 'vents', 'venue', 'venus', 'verbs', 'verge',
  'verse', 'verso', 'verst', 'verts', 'vertu', 'verve', 'vesta', 'vests', 'vetch', 'veter',
  'vexed', 'vexer', 'vexes', 'vexil', 'vials', 'viand', 'vibes', 'vicar', 'vices', 'vicus',
  'video', 'viers', 'views', 'viewy', 'vigas', 'vigia', 'vigil', 'vigor', 'viler', 'villa',
  'ville', 'villi', 'vills', 'vimen', 'vinal', 'vinas', 'vinca', 'vined', 'viner', 'vines',
  'vinic', 'vinos', 'vinyl', 'viola', 'viols', 'viper', 'viral', 'vireo', 'vires', 'virga',
  'virid', 'virls', 'virtu', 'virus', 'visas', 'vised', 'vises', 'visit', 'visor', 'vista',
  'vitae', 'vital', 'vitta', 'vivid', 'vixen', 'vizir', 'vizor', 'vocab', 'vocal', 'voces',
  'vodka', 'vodun', 'vogue', 'voice', 'voids', 'voila', 'voile', 'volar', 'voled', 'volga',
  'volta', 'volte', 'volti', 'volts', 'volva', 'vomer', 'vomit', 'voted', 'voter', 'votes',
  'vouch', 'vowed', 'vowel', 'vower', 'voxel', 'vroom', 'vuggs', 'vuggy', 'vughs', 'vulva',
  'vying',

  'wacky', 'wader', 'wafer', 'wager', 'wagon', 'waist', 'waive', 'waltz', 'waste', 'watch',
  'water', 'waved', 'waver', 'waxen', 'weary', 'weave', 'wedge', 'weedy', 'weigh', 'weird',
  'whack', 'whale', 'wharf', 'wheat', 'wheel', 'whelp', 'where', 'which', 'whiff', 'while',
  'whine', 'whirl', 'whisk', 'white', 'whole', 'whoop', 'whose', 'widen', 'widow', 'width',
  'wield', 'wilde', 'winch', 'windy', 'wiped', 'wiper', 'wiser', 'witch', 'witty', 'woken',
  'woman', 'wombs', 'women', 'woody', 'wooer', 'wordy', 'world', 'worry', 'worse', 'worst',
  'worth', 'would', 'wound', 'woven', 'wrack', 'wrath', 'wreak', 'wreck', 'wring', 'wrist',
  'write', 'wrong', 'wrote', 'wrung',

  'xenon', 'xeric', 'xerox', 'xerus', 'xylen', 'xylem', 'xylol', 'xylyl', 'xysti', 'xysts',

  'yacht', 'yager', 'yahoo', 'yanks', 'yards', 'yarns', 'yawed', 'yawls', 'yawns', 'yearn',
  'yeast', 'yells', 'yelps', 'yenta', 'yerba', 'yeses', 'yield', 'yipes', 'yodel', 'yogic',
  'yokel', 'yolky', 'youth', 'yucca', 'yucky', 'yummy',

  'zebra', 'zesty', 'zeros', 'zests', 'zesty', 'zibet', 'ziggy', 'zilch', 'zincs', 'zinky',
  'zips', 'zippy', 'zloty', 'zonal', 'zones', 'zones', 'zooey', 'zooid', 'zooks', 'zooms',
];

export const VALID_WORDS_SET: Set<string> = new Set(VALID_WORDS.map(w => w.toLowerCase().trim()));
