const WORDS = [
  { answer: 'apple', category: 'Food', hint: 'Trail starts with a crunchy fruit.' },
  { answer: 'brave', category: 'Traits', hint: 'Trail starts with courage under pressure.' },
  { answer: 'cloud', category: 'Nature', hint: 'Trail starts with sky weather.' },
  { answer: 'dream', category: 'Mind', hint: 'Trail starts with sleeping visions.' },
  { answer: 'earth', category: 'Nature', hint: 'Trail starts with the world underfoot.' },
  { answer: 'flame', category: 'Nature', hint: 'Trail starts with fire.' },
  { answer: 'grape', category: 'Food', hint: 'Trail starts with a small fruit.' },
  { answer: 'heart', category: 'Body', hint: "Trail starts with the body's pump." },
  { answer: 'light', category: 'Nature', hint: 'Trail starts with what removes darkness.' },
  { answer: 'music', category: 'Arts', hint: 'Trail starts with sound with rhythm.' },
  { answer: 'north', category: 'Place', hint: 'Trail starts with a compass direction.' },
  { answer: 'ocean', category: 'Nature', hint: 'Trail starts with a huge body of water.' },
  { answer: 'piano', category: 'Arts', hint: 'Trail starts with black and white keys.' },
  { answer: 'quiet', category: 'Traits', hint: 'Trail starts with low noise.' },
  { answer: 'river', category: 'Nature', hint: 'Trail starts with moving water.' },
  { answer: 'stone', category: 'Nature', hint: 'Trail starts with hard earth material.' },
  { answer: 'tiger', category: 'Animals', hint: 'Trail starts with a striped cat.' },
  { answer: 'unity', category: 'Ideas', hint: 'Trail starts with togetherness.' },
  { answer: 'voice', category: 'Body', hint: 'Trail starts with sound from a person.' },
  { answer: 'world', category: 'Place', hint: 'Trail starts with planet Earth.' },
  { answer: 'xenon', category: 'Science', hint: 'Trail starts with a noble gas.' },
  { answer: 'youth', category: 'Life', hint: 'Trail starts with being young.' },
  { answer: 'zebra', category: 'Animals', hint: 'Trail starts with black and white stripes.' },
  { answer: 'amber', category: 'Colors', hint: 'Trail starts with a warm yellow-orange color.' },
  { answer: 'beach', category: 'Place', hint: 'Trail starts with sand by water.' },
  { answer: 'candy', category: 'Food', hint: 'Trail starts with sweet treats.' },
  { answer: 'dance', category: 'Arts', hint: 'Trail starts with moving to music.' },
  { answer: 'eagle', category: 'Animals', hint: 'Trail starts with a strong flying bird.' },
  { answer: 'focus', category: 'Mind', hint: 'Trail starts with attention.' },
  { answer: 'ghost', category: 'Stories', hint: 'Trail starts with a spirit.' },
  { answer: 'honey', category: 'Food', hint: 'Trail starts with sweet bee food.' },
  { answer: 'image', category: 'Ideas', hint: 'Trail starts with a picture or idea.' },
  { answer: 'jolly', category: 'Traits', hint: 'Trail starts with happy mood.' },
  { answer: 'knife', category: 'Objects', hint: 'Trail starts with a sharp tool.' },
  { answer: 'lemon', category: 'Food', hint: 'Trail starts with a sour yellow fruit.' },
  { answer: 'magic', category: 'Stories', hint: 'Trail starts with spells and wonder.' },
  { answer: 'night', category: 'Time', hint: 'Trail starts after sunset.' },
  { answer: 'orbit', category: 'Science', hint: 'Trail starts with a path around a planet.' },
  { answer: 'party', category: 'Life', hint: 'Trail starts with celebration.' },
  { answer: 'queen', category: 'People', hint: 'Trail starts with a female ruler.' },
  { answer: 'robot', category: 'Tech', hint: 'Trail starts with a machine helper.' },
  { answer: 'solar', category: 'Science', hint: 'Trail starts with the Sun.' },
  { answer: 'train', category: 'Travel', hint: 'Trail starts with rails.' },
  { answer: 'urban', category: 'Place', hint: 'Trail starts with city life.' },
  { answer: 'vivid', category: 'Traits', hint: 'Trail starts with bright and clear.' },
  { answer: 'waltz', category: 'Arts', hint: 'Trail starts with a three-beat dance.' },
  { answer: 'yield', category: 'Ideas', hint: 'Trail starts with giving way.' },
  { answer: 'zesty', category: 'Traits', hint: 'Trail starts with lively flavor.' },
  { answer: 'atlas', category: 'Objects', hint: 'Trail starts with a book of maps.' },
  { answer: 'blink', category: 'Body', hint: 'Trail starts with a quick eye close.' },
  { answer: 'crown', category: 'Objects', hint: 'Trail starts with royal headwear.' },
  { answer: 'draft', category: 'Ideas', hint: 'Trail starts with an early version.' },
  { answer: 'email', category: 'Tech', hint: 'Trail starts with digital letters.' },
  { answer: 'frost', category: 'Nature', hint: 'Trail starts with frozen crystals.' },
  { answer: 'giant', category: 'Traits', hint: 'Trail starts with very large.' },
  { answer: 'hotel', category: 'Travel', hint: 'Trail starts with paid overnight rooms.' },
  { answer: 'ivory', category: 'Colors', hint: 'Trail starts with pale white.' },
  { answer: 'jungle', category: 'Place', hint: 'Trail starts with dense tropical forest.' },
  { answer: 'karma', category: 'Ideas', hint: 'Trail starts with cause and effect.' },
  { answer: 'lunar', category: 'Science', hint: 'Trail starts with the Moon.' },
  { answer: 'metal', category: 'Objects', hint: 'Trail starts with strong shiny material.' },
  { answer: 'novel', category: 'Arts', hint: 'Trail starts with a long book story.' },
  { answer: 'olive', category: 'Food', hint: 'Trail starts with a small green fruit.' },
  { answer: 'pixel', category: 'Tech', hint: 'Trail starts with one screen dot.' },
  { answer: 'quest', category: 'Stories', hint: 'Trail starts with an adventure.' },
  { answer: 'rapid', category: 'Traits', hint: 'Trail starts with very fast.' },
  { answer: 'spice', category: 'Food', hint: 'Trail starts with flavor kick.' },
  { answer: 'tower', category: 'Objects', hint: 'Trail starts with a tall structure.' },
  { answer: 'ultra', category: 'Traits', hint: 'Trail starts with extreme.' },
  { answer: 'vapor', category: 'Science', hint: 'Trail starts with gas from liquid.' },
  { answer: 'whale', category: 'Animals', hint: 'Trail starts with a huge ocean mammal.' },
  { answer: 'xerox', category: 'Objects', hint: 'Trail starts with copying paper.' },
  { answer: 'yearn', category: 'Mind', hint: 'Trail starts with strong desire.' },
  { answer: 'zenit', category: 'Science', hint: 'Trail starts with the highest point.' },
  { answer: 'build', category: 'Ideas', hint: 'Trail starts with making something.' },
  { answer: 'craft', category: 'Ideas', hint: 'Trail starts with skillful making.' },
  { answer: 'drive', category: 'Ideas', hint: 'Trail starts with inner push.' },
  { answer: 'extra', category: 'Traits', hint: 'Trail starts with more than usual.' },
  { answer: 'fresh', category: 'Traits', hint: 'Trail starts with new and clean.' },
  { answer: 'green', category: 'Colors', hint: 'Trail starts with grass color.' },
  { answer: 'happy', category: 'Traits', hint: 'Trail starts with joy.' },
  { answer: 'ideal', category: 'Ideas', hint: 'Trail starts with perfect standard.' },
  { answer: 'joint', category: 'Objects', hint: 'Trail starts with a shared connection.' },
  { answer: 'known', category: 'Ideas', hint: 'Trail starts with recognized.' },
  { answer: 'limit', category: 'Ideas', hint: 'Trail starts with a boundary.' },
  { answer: 'moral', category: 'Ideas', hint: 'Trail starts with right and wrong.' },
  { answer: 'noble', category: 'Traits', hint: 'Trail starts with honorable.' },
  { answer: 'order', category: 'Ideas', hint: 'Trail starts with arrangement.' },
  { answer: 'power', category: 'Ideas', hint: 'Trail starts with ability to act.' },
  { answer: 'quick', category: 'Traits', hint: 'Trail starts with fast.' },
  { answer: 'ratio', category: 'Science', hint: 'Trail starts with a comparison of numbers.' },
  { answer: 'sound', category: 'Science', hint: 'Trail starts with what ears hear.' },
  { answer: 'trust', category: 'Ideas', hint: 'Trail starts with belief in someone.' },
  { answer: 'union', category: 'Ideas', hint: 'Trail starts with joining together.' },
  { answer: 'value', category: 'Ideas', hint: 'Trail starts with worth.' },
  { answer: 'waste', category: 'Ideas', hint: 'Trail starts with unused leftovers.' },
  { answer: 'yield', category: 'Ideas', hint: 'Trail starts with giving way or output.' },
  { answer: 'zones', category: 'Place', hint: 'Trail starts with areas.' },
  { answer: 'asset', category: 'Ideas', hint: 'Trail starts with useful value.' },
  { answer: 'boost', category: 'Ideas', hint: 'Trail starts with a lift upward.' },
  { answer: 'claim', category: 'Ideas', hint: 'Trail starts with saying something is true.' },
  { answer: 'depth', category: 'Ideas', hint: 'Trail starts with how deep something is.' },
  { answer: 'entry', category: 'Ideas', hint: 'Trail starts with a way in.' },
  { answer: 'field', category: 'Place', hint: 'Trail starts with open land or subject.' },
  { answer: 'grade', category: 'Ideas', hint: 'Trail starts with a score level.' },
  { answer: 'habit', category: 'Life', hint: 'Trail starts with repeated behavior.' },
  { answer: 'input', category: 'Tech', hint: 'Trail starts with data going in.' },
  { answer: 'logic', category: 'Ideas', hint: 'Trail starts with clear reasoning.' },
  { answer: 'model', category: 'Ideas', hint: 'Trail starts with a simplified version.' },
  { answer: 'output', category: 'Tech', hint: 'Trail starts with result coming out.' },
  { answer: 'price', category: 'Ideas', hint: 'Trail starts with cost.' },
  { answer: 'scope', category: 'Ideas', hint: 'Trail starts with range of work.' },
  { answer: 'trial', category: 'Ideas', hint: 'Trail starts with a test.' },
  { answer: 'value', category: 'Ideas', hint: 'Trail starts with usefulness or worth.' }
];

const WORD_LIST = new Set(WORDS.map(word => word.answer.toLowerCase()));
